package component

import (
	"fmt"
	"reflect"
	"testing"
)

// TODO: DLFA-238
// Remove this when `getSolrFieldElementStringsInV1IndexerInsertionOrder()` is removed.
// This unit test is purely for illustrative purposes.  It should not be considered
// to be a regression test.  The golden files tests in ead_test.go and the DLFA-201
// cutover acceptance test provide extremely strong regression test coverage for
// this function, which is in fact temporary and will be removed after cutover.
func TestGetSolrFieldElementStringsInV1IndexerInsertionOrder(t *testing.T) {
	solrAddMessage := SolrAddMessage{
		Add: AddElement{
			DocElement{
				Address_teim:           []string{"a", "b", "c"},
				Appraisal_teim:         []string{"a", "b", "c"},
				BiogHist_teim:          []string{"a", "b", "c"},
				ChronList_teim:         []string{"a", "b", "c"},
				CollectionUnitID_ssm:   "a",
				CollectionUnitID_teim:  "a",
				Collection_sim:         "a",
				Collection_ssm:         "a",
				Collection_teim:        "a",
				ComponentChildren_bsi:  "a",
				ComponentLevel_isim:    "a",
				CorpName_ssm:           []string{"a", "b", "c"},
				CorpName_teim:          []string{"a", "b", "c"},
				Creator_sim:            []string{"a", "b", "c"},
				Creator_ssm:            []string{"a", "b", "c"},
				Creator_teim:           []string{"a", "b", "c"},
				DAO_sim:                []string{"a", "b", "c"},
				DAO_ssm:                []string{"a", "b", "c"},
				DAO_teim:               []string{"a", "b", "c"},
				DateRange_sim:          []string{"a", "b", "c"},
				EAD_ssi:                "a",
				FamName_ssm:            []string{"a", "b", "c"},
				FamName_teim:           []string{"a", "b", "c"},
				Format_sim:             []string{"a", "b", "c"},
				Format_ssm:             []string{"a", "b", "c"},
				Function_ssm:           []string{"a", "b", "c"},
				Function_teim:          []string{"a", "b", "c"},
				GenreForm_ssm:          []string{"a", "b", "c"},
				GenreForm_teim:         []string{"a", "b", "c"},
				GeogName_ssm:           []string{"a", "b", "c"},
				GeogName_teim:          []string{"a", "b", "c"},
				Heading_ssm:            []string{"a", "b", "c"},
				ID:                     "a",
				Language_sim:           "a",
				Language_ssm:           "a",
				Level_sim:              "a",
				Location_si:            "a",
				Location_ssm:           []string{"a", "b", "c"},
				MaterialType_sim:       []string{"a", "b", "c"},
				MaterialType_ssm:       []string{"a", "b", "c"},
				Name_1_teim:            []string{"a", "b", "c"},
				Name_2_teim:            []string{"a", "b", "c"},
				Name_sim:               []string{"a", "b", "c"},
				Name_ssm:               []string{"a", "b", "c"},
				Note_ssm:               []string{"a", "b", "c"},
				Note_teim:              []string{"a", "b", "c"},
				Occupation_ssm:         []string{"a", "b", "c"},
				Occupation_teim:        []string{"a", "b", "c"},
				ParentUnitTitles_ssm:   []string{"a", "b", "c"},
				ParentUnitTitles_teim:  []string{"a", "b", "c"},
				Parent_ssi:             "a",
				Parent_ssm:             []string{"a", "b", "c"},
				PersName_ssm:           []string{"a", "b", "c"},
				PersName_teim:          []string{"a", "b", "c"},
				PhysTech_teim:          []string{"a", "b", "c"},
				Place_sim:              []string{"a", "b", "c"},
				Place_ssm:              []string{"a", "b", "c"},
				Ref_ssi:                "a",
				Repository_sim:         "a",
				Repository_ssi:         "a",
				Repository_ssm:         "a",
				ScopeContent_teim:      []string{"a", "b", "c"},
				Series_si:              "a",
				Series_sim:             []string{"a", "b", "c"},
				Sort_ii:                "a",
				Subject_sim:            []string{"a", "b", "c"},
				Subject_ssm:            []string{"a", "b", "c"},
				Subject_teim:           []string{"a", "b", "c"},
				Title_ssm:              []string{"a", "b", "c"},
				Title_teim:             []string{"a", "b", "c"},
				UnitDateBulk_teim:      []string{"a", "b", "c"},
				UnitDateEnd_si:         "a",
				UnitDateEnd_sim:        []string{"a", "b", "c"},
				UnitDateEnd_ssm:        []string{"a", "b", "c"},
				UnitDateInclusive_teim: []string{"a", "b", "c"},
				UnitDateNormal_sim:     []string{"a", "b", "c"},
				UnitDateNormal_ssm:     []string{"a", "b", "c"},
				UnitDateNormal_teim:    []string{"a", "b", "c"},
				UnitDateStart_si:       "a",
				UnitDateStart_sim:      []string{"a", "b", "c"},
				UnitDateStart_ssm:      []string{"a", "b", "c"},
				UnitDate_ssm:           []string{"a", "b", "c"},
				UnitDate_teim:          []string{"a", "b", "c"},
				UnitID_ssm:             []string{"a", "b", "c"},
				UnitID_teim:            []string{"a", "b", "c"},
				UnitTitle_ssm:          []string{"a", "b", "c"},
				UnitTitle_teim:         []string{"a", "b", "c"},
			},
		},
	}

	expectedFields := []string{
		`<field name="id">a</field>`,
		`<field name="ead_ssi">a</field>`,
		`<field name="parent_ssi">a</field>`,
		`<field name="parent_ssm">a</field>`,
		`<field name="parent_ssm">b</field>`,
		`<field name="parent_ssm">c</field>`,
		`<field name="parent_unittitles_ssm">a</field>`,
		`<field name="parent_unittitles_ssm">b</field>`,
		`<field name="parent_unittitles_ssm">c</field>`,
		`<field name="parent_unittitles_teim">a</field>`,
		`<field name="parent_unittitles_teim">b</field>`,
		`<field name="parent_unittitles_teim">c</field>`,
		`<field name="component_level_isim">a</field>`,
		`<field name="component_children_bsi">a</field>`,
		`<field name="collection_sim">a</field>`,
		`<field name="collection_ssm">a</field>`,
		`<field name="collection_unitid_ssm">a</field>`,
		`<field name="level_sim">a</field>`,
		`<field name="unittitle_ssm">a</field>`,
		`<field name="unittitle_ssm">b</field>`,
		`<field name="unittitle_ssm">c</field>`,
		`<field name="unittitle_teim">a</field>`,
		`<field name="unittitle_teim">b</field>`,
		`<field name="unittitle_teim">c</field>`,
		`<field name="unitid_teim">a</field>`,
		`<field name="unitid_teim">b</field>`,
		`<field name="unitid_teim">c</field>`,
		`<field name="unitid_ssm">a</field>`,
		`<field name="unitid_ssm">b</field>`,
		`<field name="unitid_ssm">c</field>`,
		`<field name="creator_teim">a</field>`,
		`<field name="creator_teim">b</field>`,
		`<field name="creator_teim">c</field>`,
		`<field name="creator_ssm">a</field>`,
		`<field name="creator_ssm">b</field>`,
		`<field name="creator_ssm">c</field>`,
		`<field name="unitdate_normal_ssm">a</field>`,
		`<field name="unitdate_normal_ssm">b</field>`,
		`<field name="unitdate_normal_ssm">c</field>`,
		`<field name="unitdate_normal_teim">a</field>`,
		`<field name="unitdate_normal_teim">b</field>`,
		`<field name="unitdate_normal_teim">c</field>`,
		`<field name="unitdate_normal_sim">a</field>`,
		`<field name="unitdate_normal_sim">b</field>`,
		`<field name="unitdate_normal_sim">c</field>`,
		`<field name="unitdate_teim">a</field>`,
		`<field name="unitdate_teim">b</field>`,
		`<field name="unitdate_teim">c</field>`,
		`<field name="unitdate_bulk_teim">a</field>`,
		`<field name="unitdate_bulk_teim">b</field>`,
		`<field name="unitdate_bulk_teim">c</field>`,
		`<field name="unitdate_inclusive_teim">a</field>`,
		`<field name="unitdate_inclusive_teim">b</field>`,
		`<field name="unitdate_inclusive_teim">c</field>`,
		`<field name="scopecontent_teim">a</field>`,
		`<field name="scopecontent_teim">b</field>`,
		`<field name="scopecontent_teim">c</field>`,
		`<field name="bioghist_teim">a</field>`,
		`<field name="bioghist_teim">b</field>`,
		`<field name="bioghist_teim">c</field>`,
		`<field name="address_teim">a</field>`,
		`<field name="address_teim">b</field>`,
		`<field name="address_teim">c</field>`,
		`<field name="appraisal_teim">a</field>`,
		`<field name="appraisal_teim">b</field>`,
		`<field name="appraisal_teim">c</field>`,
		`<field name="phystech_teim">a</field>`,
		`<field name="phystech_teim">b</field>`,
		`<field name="phystech_teim">c</field>`,
		`<field name="chronlist_teim">a</field>`,
		`<field name="chronlist_teim">b</field>`,
		`<field name="chronlist_teim">c</field>`,
		`<field name="corpname_teim">a</field>`,
		`<field name="corpname_teim">b</field>`,
		`<field name="corpname_teim">c</field>`,
		`<field name="corpname_ssm">a</field>`,
		`<field name="corpname_ssm">b</field>`,
		`<field name="corpname_ssm">c</field>`,
		`<field name="famname_teim">a</field>`,
		`<field name="famname_teim">b</field>`,
		`<field name="famname_teim">c</field>`,
		`<field name="famname_ssm">a</field>`,
		`<field name="famname_ssm">b</field>`,
		`<field name="famname_ssm">c</field>`,
		`<field name="function_teim">a</field>`,
		`<field name="function_teim">b</field>`,
		`<field name="function_teim">c</field>`,
		`<field name="function_ssm">a</field>`,
		`<field name="function_ssm">b</field>`,
		`<field name="function_ssm">c</field>`,
		`<field name="genreform_teim">a</field>`,
		`<field name="genreform_teim">b</field>`,
		`<field name="genreform_teim">c</field>`,
		`<field name="genreform_ssm">a</field>`,
		`<field name="genreform_ssm">b</field>`,
		`<field name="genreform_ssm">c</field>`,
		`<field name="geogname_teim">a</field>`,
		`<field name="geogname_teim">b</field>`,
		`<field name="geogname_teim">c</field>`,
		`<field name="geogname_ssm">a</field>`,
		`<field name="geogname_ssm">b</field>`,
		`<field name="geogname_ssm">c</field>`,
		// This got moved to before `name_teim` in this DLFA-238 removal commit:
		// https://github.com/NYULibraries/go-ead-indexer/commit/42cab880c7e87982db8c5c1a587f8074ff39fe3f
		// I only vaguely remember why I did this, but I think it's because I
		// came across a case where it appeared in this position.  It is defintely
		// the case that it appears after `name_teim` for many EAD files, and
		// perhaps this is so in the majority of them.  Just need to make this
		// test pass for now.  The function under test will soon be deleted anyway.
		`<field name="name_ssm">a</field>`,
		`<field name="name_ssm">b</field>`,
		`<field name="name_ssm">c</field>`,
		`<field name="name_teim">a</field>`,
		`<field name="name_teim">b</field>`,
		`<field name="name_teim">c</field>`,
		`<field name="occupation_teim">a</field>`,
		`<field name="occupation_teim">b</field>`,
		`<field name="occupation_teim">c</field>`,
		`<field name="occupation_ssm">a</field>`,
		`<field name="occupation_ssm">b</field>`,
		`<field name="occupation_ssm">c</field>`,
		`<field name="persname_teim">a</field>`,
		`<field name="persname_teim">b</field>`,
		`<field name="persname_teim">c</field>`,
		`<field name="persname_ssm">a</field>`,
		`<field name="persname_ssm">b</field>`,
		`<field name="persname_ssm">c</field>`,
		`<field name="subject_teim">a</field>`,
		`<field name="subject_teim">b</field>`,
		`<field name="subject_teim">c</field>`,
		`<field name="subject_ssm">a</field>`,
		`<field name="subject_ssm">b</field>`,
		`<field name="subject_ssm">c</field>`,
		`<field name="title_teim">a</field>`,
		`<field name="title_teim">b</field>`,
		`<field name="title_teim">c</field>`,
		`<field name="title_ssm">a</field>`,
		`<field name="title_ssm">b</field>`,
		`<field name="title_ssm">c</field>`,
		`<field name="note_teim">a</field>`,
		`<field name="note_teim">b</field>`,
		`<field name="note_teim">c</field>`,
		`<field name="note_ssm">a</field>`,
		`<field name="note_ssm">b</field>`,
		`<field name="note_ssm">c</field>`,
		`<field name="dao_teim">a</field>`,
		`<field name="dao_teim">b</field>`,
		`<field name="dao_teim">c</field>`,
		`<field name="dao_ssm">a</field>`,
		`<field name="dao_ssm">b</field>`,
		`<field name="dao_ssm">c</field>`,
		`<field name="ref_ssi">a</field>`,
		`<field name="repository_ssi">a</field>`,
		`<field name="repository_sim">a</field>`,
		`<field name="repository_ssm">a</field>`,
		`<field name="format_sim">a</field>`,
		`<field name="format_sim">b</field>`,
		`<field name="format_sim">c</field>`,
		`<field name="format_ssm">a</field>`,
		`<field name="format_ssm">b</field>`,
		`<field name="format_ssm">c</field>`,
		`<field name="location_ssm">a</field>`,
		`<field name="location_ssm">b</field>`,
		`<field name="location_ssm">c</field>`,
		`<field name="location_si">a</field>`,
		`<field name="creator_sim">a</field>`,
		`<field name="creator_sim">b</field>`,
		`<field name="creator_sim">c</field>`,
		`<field name="name_sim">a</field>`,
		`<field name="name_sim">b</field>`,
		`<field name="name_sim">c</field>`,
		`<field name="name_teim">a</field>`,
		`<field name="name_teim">b</field>`,
		`<field name="name_teim">c</field>`,
		`<field name="dao_sim">a</field>`,
		`<field name="dao_sim">b</field>`,
		`<field name="dao_sim">c</field>`,
		`<field name="place_ssm">a</field>`,
		`<field name="place_ssm">b</field>`,
		`<field name="place_ssm">c</field>`,
		`<field name="place_sim">a</field>`,
		`<field name="place_sim">b</field>`,
		`<field name="place_sim">c</field>`,
		`<field name="subject_sim">a</field>`,
		`<field name="subject_sim">b</field>`,
		`<field name="subject_sim">c</field>`,
		`<field name="collection_teim">a</field>`,
		`<field name="collection_unitid_teim">a</field>`,
		`<field name="series_sim">a</field>`,
		`<field name="series_sim">b</field>`,
		`<field name="series_sim">c</field>`,
		`<field name="series_si">a</field>`,
		`<field name="material_type_sim">a</field>`,
		`<field name="material_type_sim">b</field>`,
		`<field name="material_type_sim">c</field>`,
		`<field name="material_type_ssm">a</field>`,
		`<field name="material_type_ssm">b</field>`,
		`<field name="material_type_ssm">c</field>`,
		`<field name="heading_ssm">a</field>`,
		`<field name="heading_ssm">b</field>`,
		`<field name="heading_ssm">c</field>`,
		`<field name="unitdate_start_sim">a</field>`,
		`<field name="unitdate_start_sim">b</field>`,
		`<field name="unitdate_start_sim">c</field>`,
		`<field name="unitdate_start_ssm">a</field>`,
		`<field name="unitdate_start_ssm">b</field>`,
		`<field name="unitdate_start_ssm">c</field>`,
		`<field name="unitdate_start_si">a</field>`,
		`<field name="unitdate_end_sim">a</field>`,
		`<field name="unitdate_end_sim">b</field>`,
		`<field name="unitdate_end_sim">c</field>`,
		`<field name="unitdate_end_ssm">a</field>`,
		`<field name="unitdate_end_ssm">b</field>`,
		`<field name="unitdate_end_ssm">c</field>`,
		`<field name="unitdate_end_si">a</field>`,
		`<field name="unitdate_ssm">a</field>`,
		`<field name="unitdate_ssm">b</field>`,
		`<field name="unitdate_ssm">c</field>`,
		`<field name="date_range_sim">a</field>`,
		`<field name="date_range_sim">b</field>`,
		`<field name="date_range_sim">c</field>`,
		`<field name="language_sim">a</field>`,
		`<field name="language_ssm">a</field>`,
		`<field name="sort_ii">a</field>`,
	}

	fields := getSolrFieldElementStringsInV1IndexerInsertionOrder(solrAddMessage)
	if !reflect.DeepEqual(fields, expectedFields) {
		actual := fmt.Sprintf("%v", fields)
		expected := fmt.Sprintf("%v", expectedFields)
		t.Errorf("\nExpected: %s\n\nActual:   %s", expected, actual)
	}
}
