package testutils

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const FakeSolrHostAndPort = "fake-solr-host.library.nyu.edu:8080"
const TestEAD = "edip/mos_2024"

var hostHeaderRegExp = regexp.MustCompile("Host: 127.0.0.1:[0-9]+")
var idRegExp = regexp.MustCompile(`<field name="id">([a-z0-9_-]+)</field>`)

var tmpFilesDirPath = filepath.Join("testdata", "tmp", "actual")

func Clean() error {
	err := os.RemoveAll(tmpFilesDirPath)
	if err != nil {
		return err
	}

	err = os.MkdirAll(tmpFilesDirPath, 0700)
	if err != nil {
		return err
	}

	_, err = os.Create(filepath.Join(tmpFilesDirPath, ".gitkeep"))
	if err != nil {
		return err
	}

	return nil
}

func GetActualFileContents(testEAD string, fileID string) (string, error) {
	actualFile := tmpFile(testEAD, fileID)

	bytes, err := os.ReadFile(actualFile)
	if err != nil {
		return "", err
	}

	return string(bytes), nil
}

func GetExpectedPOSTRequestString(body string) string {
	return fmt.Sprintf("%s\n\n%s", getPOSTRequestHTTPHeadersString(body), body)
}

func GetID(dumpedRequest []byte) (string, error) {
	matches := idRegExp.FindStringSubmatch(string(dumpedRequest))

	if len(matches) > 1 {
		return matches[1], nil
	} else {
		return "", nil
	}
}

// To match actual test request to golden values generated by `GetExpectedPOSTRequestString()`,
// we need to:
// 1) Replace the Host header with the dynamically generated Solr fake
// address with the expected fake address
// 2) Remove the carriage returns that Go HTTP client uses in the line breaks.
// (The HTTP spec statest that applications must accept CR, LF, and CRLF:
// https://www.rfc-editor.org/rfc/rfc2616#section-2.2)
func MassagedGoHTTPClientRequest(request string) string {
	massagedHostHeaderRequest := hostHeaderRegExp.ReplaceAllString(request,
		"Host: "+FakeSolrHostAndPort)

	return strings.ReplaceAll(massagedHostHeaderRequest, "\r", "")
}

func getPOSTRequestHTTPHeadersString(body string) string {
	// `Content-Length` should be size in bytes, not characters, so using
	// `len()` is correct, even if multi-rune characters are used in `body`.
	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length
	var charLength = len(body)

	var postRequestHTTPHeadersString = fmt.Sprintf(
		`POST /solr/findingaids/update?wt=json&indent=true HTTP/1.1
Host: %s
Accept-Encoding: gzip
Content-Length: %s
Content-Type: text/xml
User-Agent: Go-http-client/1.1`, FakeSolrHostAndPort, strconv.Itoa(charLength))

	return postRequestHTTPHeadersString
}

func tmpFile(testEAD string, fileID string) string {
	return filepath.Join(tmpFilesDirPath, testEAD, fileID+".xml")
}

func writeActualSolrRequestToTmp(testEAD string, fileID string, actual string) error {
	tmpFile := tmpFile(testEAD, fileID)
	err := os.MkdirAll(filepath.Dir(tmpFile), 0755)
	if err != nil {
		return err
	}

	return os.WriteFile(tmpFile, []byte(actual), 0644)
}
