FROM golang:1.23

RUN update-ca-certificates

WORKDIR /app

RUN apt-get update -y && apt-get install -y libxml2-dev pkg-config
RUN go install golang.org/x/lint/golint@latest
COPY . . 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o app .

CMD [ "go", "test", "./...", "-cover" ]
