// Code generated by pkg/index/testsupport/gen-repo.bash. DO NOT EDIT.

package testutils

// ------------------------------------------------------------------------------
// git repo fixture constants shared by cmd/index and pkg/index tests
// ------------------------------------------------------------------------------

/*
	# Commit history from test fixture
	abcd91ab50862cc1dc59e7297ecded651883a1e1 Updating README.md
	75dcc7b44219559f5794359627fb979c839ceea3 Updating nyuad/ad_mc_019.xml, Deleting file tamwag/tam_143.xml EADID='tam_143', Updating edip/mos_2024.xml, Deleting file cbh/arc_212_plymouth_beecher.xml EADID='arc_212_plymouth_beecher', Updating akkasah/ad_mc_030.xml
	77c9c66337212fe86b235ebe089294c1d9f1e170 Updating tamwag/tam_143.xml, Updating cbh/arc_212_plymouth_beecher.xml
	1556117167d78fbb0b7b9d0e09247a78a5cc3cd9 Deleting file fales/mss_420.xml EADID='mss_420', Updating fales/mss_420.xml
	5b13f670d25fe053530ac18aeafc7339ce187034 Updating fales/mss_420.xml
	24becf5d3ae251cb74a82ee19f1310e3cd0de2c8 Deleting file fales/mss_460.xml EADID='mss_460'
	fa46edc88ce18e09da2be593417703346c6b0abc Updating fales/mss_460.xml
	039d90e0bde64466379208e7461e7f2a19913472 Deleting file akkasah/ad_mc_030.xml EADID='ad_mc_030', Deleting file cbh/arc_212_plymouth_beecher.xml EADID='arc_212_plymouth_beecher', Deleting file edip/mos_2024.xml EADID='mos_2024', Deleting file fales/mss_420.xml EADID='mss_420', Deleting file fales/mss_460.xml EADID='mss_460', Deleting file nyhs/ms256_harmon_hendricks_goldstone.xml EADID='ms256_harmon_hendricks_goldstone', Deleting file nyhs/ms347_foundling_hospital.xml EADID='ms347_foundling_hospital', Deleting file nyuad/ad_mc_019.xml EADID='ad_mc_019', Deleting file tamwag/tam_143.xml EADID='tam_143'
	a70140fab0efc8d2c865c1c586698deefe0ae375 Updating akkasah/ad_mc_030.xml, Updating cbh/arc_212_plymouth_beecher.xml, Updating edip/mos_2024.xml, Updating fales/mss_420.xml, Updating fales/mss_460.xml, Updating nyhs/ms256_harmon_hendricks_goldstone.xml, Updating nyhs/ms347_foundling_hospital.xml, Updating nyuad/ad_mc_019.xml, Updating tamwag/tam_143.xml
*/

// hashes from the git-repo fixture (in order of commits)
const AddAllHash = "a70140fab0efc8d2c865c1c586698deefe0ae375"
const DeleteAllHash = "039d90e0bde64466379208e7461e7f2a19913472"
const AddOneHash = "fa46edc88ce18e09da2be593417703346c6b0abc"
const DeleteOneHash = "24becf5d3ae251cb74a82ee19f1310e3cd0de2c8"
const DeleteModifyAddHash = "1556117167d78fbb0b7b9d0e09247a78a5cc3cd9"
const AddTwoHash = "77c9c66337212fe86b235ebe089294c1d9f1e170"
const AddThreeDeleteTwoHash = "75dcc7b44219559f5794359627fb979c839ceea3"
const NoEADFilesInCommitHash = "abcd91ab50862cc1dc59e7297ecded651883a1e1"
