// Code generated by pkg/index/testsupport/gen-repo.bash. DO NOT EDIT.

package testutils

// ------------------------------------------------------------------------------
// git repo fixture constants shared by cmd/index and pkg/index tests
// ------------------------------------------------------------------------------

/*
	# Commit history from test fixture
	3df29b08307d939ca2d78e88c7ff58c2303d3a58 Updating README.md
	60fe0ab2ef487ef7e5fb7506882ed4a9f4bd5659 Updating nyuad/ad_mc_019.xml, Deleting file tamwag/tam_143.xml EADID='tam_143', Updating edip/mos_2024.xml, Deleting file cbh/arc_212_plymouth_beecher.xml EADID='arc_212_plymouth_beecher', Updating akkasah/ad_mc_030.xml
	b6a37368c3d1ce52246b2e6b0266c504b978895a Updating tamwag/tam_143.xml, Updating cbh/arc_212_plymouth_beecher.xml
	1b89d86ac94aea3ca0ceac45b20840edb2a4d575 Deleting file fales/mss_420.xml EADID='mss_420', Updating fales/mss_420.xml
	2d541e347910489c2182c19f45501a35bca92d61 Updating fales/mss_420.xml
	1d608596eedf1baf47b5f2dd21f8be59d2b72aef Deleting file fales/mss_460.xml EADID='mss_460'
	92e62027df18e069c975f2d2e08bb3e0bf29a4a3 Updating fales/mss_460.xml
	03b0fed905b62a916f10d3b8e3cd170e3bc71b5a Deleting file akkasah/ad_mc_030.xml EADID='ad_mc_030', Deleting file cbh/arc_212_plymouth_beecher.xml EADID='arc_212_plymouth_beecher', Deleting file edip/mos_2024.xml EADID='mos_2024', Deleting file fales/mss_420.xml EADID='mss_420', Deleting file fales/mss_460.xml EADID='mss_460', Deleting file nyhs/ms256_harmon_hendricks_goldstone.xml EADID='ms256_harmon_hendricks_goldstone', Deleting file nyhs/ms347_foundling_hospital.xml EADID='ms347_foundling_hospital', Deleting file nyuad/ad_mc_019.xml EADID='ad_mc_019', Deleting file tamwag/tam_143.xml EADID='tam_143'
	4c96e78ae68001067397f15189a9f2e7db73ce0c Updating akkasah/ad_mc_030.xml, Updating cbh/arc_212_plymouth_beecher.xml, Updating edip/mos_2024.xml, Updating fales/mss_420.xml, Updating fales/mss_460.xml, Updating nyhs/ms256_harmon_hendricks_goldstone.xml, Updating nyhs/ms347_foundling_hospital.xml, Updating nyuad/ad_mc_019.xml, Updating tamwag/tam_143.xml
*/

// hashes from the git-repo fixture (in order of commits)
const AddAllHash = "4c96e78ae68001067397f15189a9f2e7db73ce0c"
const DeleteAllHash = "03b0fed905b62a916f10d3b8e3cd170e3bc71b5a"
const AddOneHash = "92e62027df18e069c975f2d2e08bb3e0bf29a4a3"
const DeleteOneHash = "1d608596eedf1baf47b5f2dd21f8be59d2b72aef"
const DeleteModifyAddHash = "1b89d86ac94aea3ca0ceac45b20840edb2a4d575"
const AddTwoHash = "b6a37368c3d1ce52246b2e6b0266c504b978895a"
const AddThreeDeleteTwoHash = "60fe0ab2ef487ef7e5fb7506882ed4a9f4bd5659"
const NoEADFilesInCommitHash = "3df29b08307d939ca2d78e88c7ff58c2303d3a58"
