docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2024.02
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

hermes_deploy: &hermes_deploy
    run:
      name: Deploy via Hermes
      command: |
        docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master createJob -job=fake-cronjob


version: 2.1
jobs:
  build-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build test
          command: |
            docker compose build test
      - run:
          name: Check formatting
          command: |
            docker compose run test gofmt -l .
            test -z "$(docker compose run test gofmt -l .)"
            docker compose run test go vet
      - run:
          name: Test
          command: |
            docker compose run test
      - run:
          name: Build app
          command: |
            docker compose build
      - <<: *auth_quay
      - run:
          name: Push image
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag eadindexer quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}
            docker tag eadindexer quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

  deploy-dev:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Export Hermes Dev env vars
          command: |
            echo 'export HERMES_HOST=https://hermes-dev.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_DEV' >> $BASH_ENV
      - <<: *hermes_deploy

workflows:
  version: 2
  build-test:
    jobs:
      - build-test
      - deploy-dev:
          requires:
            - build-test


