docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2024.02
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io


version: 2.1
jobs:
  build-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build test
          command: |
            docker compose build test
      - run:
          name: Check formatting
          command: |
            docker compose run test gofmt -l .
            test -z "$(docker compose run test gofmt -l .)"
            docker compose run test go vet
      - run:
          name: Test
          command: |
            docker compose run test
      - run:
          name: Build app
          command: |
            docker compose build
      - <<: *auth_quay
      - run:
          name: Push image
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag eadindexer quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}
            docker tag eadindexer quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/go-ead-indexer:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

workflows:
  version: 2
  build-test:
    jobs:
      - build-test


